export type ClassData = {
  id: string
  name: string
  shortName: string
  sport: 'track' | 'badminton' | 'dance' | 'tennis' | 'other'
  venue: string
  venueId: 'shiei' | 'nakamura' | 'seibu' | 'inoki' | 'sporec' | 'sogo'
  day: string
  time: string
  age: string
  price: number
  instructor: string
  description: string
  tags?: string[]
  isNew?: boolean
  isPopular?: boolean
}

export const venues = [
  { id: 'shiei', name: '市営陸上競技場', shortName: '市営陸上', color: '#185FA5', lat: 36.5613, lng: 136.6486, area: '中心部' },
  { id: 'nakamura', name: '中村町小学校', shortName: '中村町小', color: '#854F0B', lat: 36.5468, lng: 136.6445, area: '中村町' },
  { id: 'seibu', name: '西部緑地公園陸上競技場', shortName: '西部緑地', color: '#2A7B5B', lat: 36.5783, lng: 136.6167, area: '西部' },
  { id: 'inoki', name: '稲置学園総合運動場', shortName: '稲置学園', color: '#993C1D', lat: 36.5868, lng: 136.6724, area: '東部' },
  { id: 'sporec', name: '健民スポレクプラザ', shortName: 'スポレク', color: '#534AB7', lat: 36.5529, lng: 136.6263, area: '泉野' },
  { id: 'sogo', name: '金沢市総合体育館', shortName: '市総合', color: '#A32D2D', lat: 36.5561, lng: 136.6558, area: '中心部' },
] as const

export const trackClasses: ClassData[] = [
  {
    id: 'kakekko-hop',
    name: 'かけっこ塾（ホップ・ステップ・ジャンプ）',
    shortName: 'かけっこ塾',
    sport: 'track',
    venue: '稲置学園総合運動場',
    venueId: 'inoki',
    day: '水',
    time: '19:30〜20:30',
    age: '小2〜中学生',
    price: 6600,
    instructor: '金沢星稜大学陸上競技部、スタータススタッフ',
    description: '金沢星稜大学陸上部の大学生が楽しく指導！専用の陸上競技場で、走る喜びを体感しながら運動能力を伸ばせる人気教室！',
    tags: ['人気No.1'],
    isPopular: true,
  },
  {
    id: 'kakekko-approach',
    name: 'かけっこ塾（アプローチ）',
    shortName: 'アプローチ',
    sport: 'track',
    venue: '稲置学園総合運動場',
    venueId: 'inoki',
    day: '水',
    time: '19:30〜20:30',
    age: '年中〜小1',
    price: 6600,
    instructor: '星稜大学陸上競技部、スタータススタッフ',
    description: 'かけっこ塾と合同開催。小さなお子様向けのやさしいプログラム。',
  },
  {
    id: 'izumi-junior',
    name: '陸上 泉（ジュニア）',
    shortName: '泉ジュニア',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '木',
    time: '18:00〜19:00',
    age: '小学〜中学生',
    price: 6600,
    instructor: '山本 勝裕（やまティー）',
    description: 'エビデンスと理論で一歩進んだレッスン。フィードバックシートなど手厚い指導が定評。',
  },
  {
    id: 'izumi-kids',
    name: '陸上 泉（キッズ）',
    shortName: '泉キッズ',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '木',
    time: '17:00〜18:00',
    age: '小学生',
    price: 6600,
    instructor: '松井 久（Qちゃん）',
    description: 'スポーツ、陸上を好きになる楽しいプログラム。走り、投げ、跳びを行い、親密な指導が定評。',
  },
  {
    id: 'seibu-junior',
    name: '陸上 西部（ジュニア）',
    shortName: '西部ジュニア',
    sport: 'track',
    venue: '西部緑地公園陸上競技場',
    venueId: 'seibu',
    day: '水',
    time: '18:00〜19:00',
    age: '小学〜中学生',
    price: 6600,
    instructor: '須田崇',
    description: '',
  },
  {
    id: 'seibu-kids',
    name: '陸上 西部（キッズ）',
    shortName: '西部キッズ',
    sport: 'track',
    venue: '西部緑地公園陸上競技場',
    venueId: 'seibu',
    day: '水',
    time: '17:00〜18:00',
    age: '小学生',
    price: 6600,
    instructor: '松井 久（Qちゃん）',
    description: '',
  },
  {
    id: 'nakamura-kakekko',
    name: '陸上 中村町（かけっこ・キッズ）',
    shortName: 'かけっこキッズ',
    sport: 'track',
    venue: '中村町小学校',
    venueId: 'nakamura',
    day: '月',
    time: '17:00〜18:00',
    age: '小学生',
    price: 5500,
    instructor: '松井 久（Qちゃん）',
    description: '',
  },
  {
    id: 'nakamura-junior',
    name: '陸上 中村町（かけっこ・ジュニア）',
    shortName: 'かけっこジュニア',
    sport: 'track',
    venue: '中村町小学校',
    venueId: 'nakamura',
    day: '月',
    time: '17:00〜18:00',
    age: '小学〜中学生',
    price: 5500,
    instructor: '松井 久（Qちゃん）',
    description: '',
  },
  {
    id: 'nakamura-marathon-kids',
    name: '陸上 中村町（マラソン・キッズ）',
    shortName: 'マラソンキッズ',
    sport: 'track',
    venue: '中村町小学校',
    venueId: 'nakamura',
    day: '火',
    time: '17:00〜18:00',
    age: '小学生',
    price: 5500,
    instructor: '松井 久（Qちゃん）',
    description: '',
  },
  {
    id: 'nakamura-marathon-junior',
    name: '陸上 中村町（マラソン・ジュニア）',
    shortName: 'マラソンジュニア',
    sport: 'track',
    venue: '中村町小学校',
    venueId: 'nakamura',
    day: '火',
    time: '17:00〜18:00',
    age: '小学〜中学生',
    price: 5500,
    instructor: '松井 久（Qちゃん）',
    description: '',
  },
  {
    id: 'sporec-kids',
    name: '陸上 スポレク（キッズ）',
    shortName: 'スポレクキッズ',
    sport: 'track',
    venue: '健民スポレクプラザ',
    venueId: 'sporec',
    day: '火',
    time: '17:00〜18:00',
    age: '年中〜小学生',
    price: 5500,
    instructor: '須田崇',
    description: '',
  },
  {
    id: 'sporec-junior',
    name: '陸上 スポレク（ジュニア）',
    shortName: 'スポレクジュニア',
    sport: 'track',
    venue: '健民スポレクプラザ',
    venueId: 'sporec',
    day: '火',
    time: '18:00〜19:00',
    age: '小学生',
    price: 5500,
    instructor: '須田崇',
    description: '',
  },
  {
    id: 'marathon-junior',
    name: 'マラソン塾（ジュニア）',
    shortName: 'マラソン塾Jr',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '金',
    time: '19:00〜20:00',
    age: '小学〜中学生',
    price: 6600,
    instructor: '松井 久',
    description: '',
  },
  {
    id: 'otona-marathon',
    name: '大人のマラソン塾',
    shortName: '大人マラソン',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '木',
    time: '19:30〜21:00',
    age: '中学〜大人',
    price: 6600,
    instructor: '松井 久（Qちゃん） 他',
    description: 'サブ4からマラソン完走、健康維持まで幅広く対応。',
  },
  {
    id: 'inclusive-running',
    name: 'インクルーシブランニング',
    shortName: 'インクルーシブ',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '月',
    time: '18:30〜20:00',
    age: '小学〜大人',
    price: 3300,
    instructor: '橋本 祐之 他',
    description: '障がいの有無にかかわらず参加可能。スポット参加OK。',
  },
  {
    id: 'shunpu',
    name: '春風クラブ',
    shortName: '春風クラブ',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '水・金',
    time: '18:30〜20:00',
    age: '中学〜大人',
    price: 3300,
    instructor: '橋本 祐之 他',
    description: '障がいのある方が安心して陸上を楽しめるクラブ。',
  },
  {
    id: 'rubugeru',
    name: 'るぶげる親子陸上塾',
    shortName: 'るぶげる親子',
    sport: 'track',
    venue: '金沢市営陸上競技場',
    venueId: 'shiei',
    day: '土・日',
    time: '13:00〜14:30',
    age: '小学〜大人',
    price: 8800,
    instructor: '山本 勝裕（やまティー）',
    description: '親子で向き合い、成長を真剣に、楽しく取り組める時間。',
    isNew: true,
  },
]

// マトリクス表用のヘルパー
export const days = ['月', '火', '水', '木', '金', '土・日'] as const

export function getClassesByVenueAndDay(venueId: string, day: string): ClassData[] {
  return trackClasses.filter(c => c.venueId === venueId && c.day.includes(day.replace('・日', '').replace('土・', '')))
}

export function getClassesByVenue(venueId: string): ClassData[] {
  return trackClasses.filter(c => c.venueId === venueId)
}
